name: Pipeline
run-name: Pipeline by @${{ github.actor }}

on:
  push:
    branches:
      - master
  pull_request:
      branches:
          - master

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
